In [3]:
#この章で使用するライブラリ
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

# 可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

#小数点3位までの表示
%precision 3

'%.3f'

In [4]:
#線形代数用のライブラリ
import scipy.linalg as linalg

#最適化計算(最小値）用の関数
from scipy.optimize import minimize_scalar

In [8]:
matrix = np.array([[1,-1,-1],[-1,1,-1],[-1,-1,1]])

#行列式(determinant)
print('行列式')
print(linalg.det(matrix))

行列式
-4.0


In [9]:
#逆行列(inverse matrix)
print(linalg.inv(matrix))

[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


In [10]:
#元の行列と逆行列の積は単位行列のはず
print(matrix.dot(linalg.inv(matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
#ニュートン法

#関数の定義
def my_function(x):
    return (x ** 2 + 2 * x + 1)

#ニュートン法の読み込み
from scipy.optimize import newton

#計算実行
print(newton(my_function, 0))

-0.9999999852953906
