# 2-2 Numpyの基礎
## 2-2-1 Numpyのインポート

In [15]:
#この章で使用するライブラリ
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

In [16]:
# 可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

#小数点3位までの表示
%precision 377

'%.377f'

## 2-2-2 配列操作
### 2-1 配列

In [17]:
data = np.array([9,2,3,4,10,6,7,8,1,5])
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

### 2-2 データ型

In [18]:
data.dtype

dtype('int64')

### 2-3 次元数と要素数

In [19]:
print('次元数:', data.ndim)
print('要素数:', data.size)

次元数: 1
要素数: 10


### 2-4 全ての要素に対する計算

In [20]:
data * 2

array([18,  4,  6,  8, 20, 12, 14, 16,  2, 10])

In [21]:
# .arrayはメソッド（関数）なので中括弧が必要
print('掛け算:',np.array([1,2,3,4,5,6,7,8,9,10]) * np.array([10,9,8,7,6,5,4,3,2,1]))

掛け算: [10 18 24 28 30 30 28 24 18 10]


In [22]:
print('累乗:',np.array([1,2,3,4,5,6,7,8,9,10]) ** 2)

累乗: [  1   4   9  16  25  36  49  64  81 100]


In [23]:
print('割り算:',np.array([1,2,3,4,5,6,7,8,9,10]) / np.array([10,9,8,7,6,5,4,3,2,1]))

割り算: [ 0.1                 0.2222222222222222  0.375
  0.5714285714285714  0.8333333333333334  1.2
  1.75                2.6666666666666665  4.5
 10.                ]


### 2-5 並び替え（ソート）

In [24]:
print(data)
data.sort()
data

[ 9  2  3  4 10  6  7  8  1  5]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
#逆順のソート
#[n,m,s] n番目からm-1番目をsずつ飛ばして取り出す。n,mを省略すると全ての意味になる
data[::-1].sort()
data

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### 2-6 最小、最大、合計、積上の計算

In [26]:
#最小値
print('min:', data.min())
#最大値
print('max:', data.max())
#合計
print('sum:', data.sum())
#積み上げ
print('cum:', data.cumsum())
#積み上げ割合
print('ratio:', data.cumsum()/ data.sum())

min: 1
max: 10
sum: 55
cum: [10 19 27 34 40 45 49 52 54 55]
ratio: [0.18181818181818182 0.34545454545454546 0.4909090909090909
 0.6181818181818182  0.7272727272727273  0.8181818181818182
 0.8909090909090909  0.9454545454545454  0.9818181818181818
 1.                 ]


## 2-2-3 乱数
### 3-1 乱数のシード
### 3-2 乱数の発生

In [28]:
#乱数
random.seed(0)

#正規分布(平均0,分散1）の乱数を10個発生
rnd_data = random.randn(10)

print('乱数10個の配列:', rnd_data)

乱数10個の配列: [ 1.764052345967664    0.4001572083672233   0.9787379841057392
  2.240893199201458    1.8675579901499675  -0.977277879876411
  0.9500884175255894  -0.1513572082976979  -0.10321885179355784
  0.41059850193837233]


### 3-3 データのランダムな抽出

In [29]:
#データのランダム抽出
data = np.array([9,2,3,4,10,6,7,8,1,5])
print(random.choice(data, 10))
print(random.choice(data, 10, replace=False))

[ 7  8  8  1  2  6  5  1  5 10]
[10  2  7  8  3  1  6  5  9  4]


#### 【column】 Numpyは高速

In [30]:
# #column
# #超高速なnumpy!!

# N = 10 ** 6
# #"_"と書くのはその後に変数を使用しないときの慣習
# normal_data = [random.random() for _ in range(N)]

# #numpy ver.
# nunpy_random_data = np.array(normal_data)

# #普通の処理
# %timeit sum(normal_data)

# #numpyの処理
# %timeit np.sum(nunpy_random_data)

## 2-2-4 行列

In [31]:
#ここからは行列
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
array1 = np.arange(9).reshape(3,3)
print(array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [33]:
#1行目
array1[0,:]

array([0, 1, 2])

In [34]:
#1列目
array1[:,0]

array([0, 3, 6])

### 4-1 行列の演算

In [35]:
array2 = np.arange(9,18).reshape(3,3)
print(array2)

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [36]:
#行列の積（内積＝dot product）
np.dot(array1,array2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [37]:
#要素同士の積
array1 * array2

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [38]:
#要素が0や1の行列を作る
print(np.zeros((2,3), dtype = np.int64))
print(np.ones((2,3), dtype = np.float64))

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


### 章末の練習問題

In [44]:
#練習問題2-1
array21 = np.array([i for i in range(51)])
print(array21.sum())

1275


In [45]:
#練習問題2-2:正規分布に基づく乱数生成
array22 = random.randn(10)
print('最大値 : {0},最小値 : {1}, 合計 : {2}'.format(array22.max(), array22.min(), array22.sum()))
print(array22)

最大値 : 1.5327792143584575,最小値 : -1.980796468223927, 合計 : 0.3336772007572325
[ 0.04575851730144607 -0.1871838500258336   1.5327792143584575
  1.469358769900285    0.1549474256969163   0.37816251960217356
 -0.8877857476301128  -1.980796468223927   -0.3479121493261526
  0.15634896910398005]


In [46]:
#練習問題2-3 : 行列を作成し、要素を2乗してみよう
array23 = np.array([3 for _ in range(9)]).reshape(3,3)
print(array23)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [43]:
array23 ** 2

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])