# 2-3 Scipyの基礎
## 2-3-1 Scipyのライブラリのインポート

In [2]:
#この章で使用するライブラリ
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

# 可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

#小数点3位までの表示
%precision 3

'%.3f'

## 2-3-2 行列計算
### 2-1 行列式と逆行列の計算

In [4]:
#線形代数用のライブラリ
import scipy.linalg as linalg

#最適化計算(最小値）用の関数
from scipy.optimize import minimize_scalar

In [5]:
matrix = np.array([[1,-1,-1],[-1,1,-1],[-1,-1,1]])

#行列式(determinant)
print('行列式')
print(linalg.det(matrix))

行列式
-4.0


In [6]:
#逆行列(inverse matrix)
print(linalg.inv(matrix))

[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


In [7]:
#元の行列と逆行列の積は単位行列のはず
print(matrix.dot(linalg.inv(matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 2-2 固有値と固有ベクトル

In [17]:
# 固有値を英語でeigenvalue,固有ベクトルをeigenvectorという
eig_value, eig_vector = linalg.eig(matrix)

print ('固有値')
print (eig_value)
print ('固有ベクトル')
print (eig_vector)

固有値
[ 6.   +0.j -1.414+0.j  1.414+0.j]
固有ベクトル
[[-0.577 -0.722  0.16 ]
 [-0.577 -0.143 -0.811]
 [-0.577  0.677  0.563]]


## 2-3-3 ニュートン法
### 3-1 方程式の解を求める

In [18]:
#ニュートン法

#関数の定義
def my_function(x):
    return (x ** 2 + 2 * x + 1)

#ニュートン法の読み込み
from scipy.optimize import newton

#計算実行
print(newton(my_function, 0))

-0.9999999852953906


### 3-2 最小値を求める

In [19]:
#最小値を求める : brent法を利用
print(minimize_scalar(my_function, method = 'Brent'))

 message: 
          Optimization terminated successfully;
          The returned value satisfies the termination criteria
          (using xtol = 1.48e-08 )
 success: True
     fun: 0.0
       x: -1.0000000000000002
     nit: 4
    nfev: 8


["根の探索アルゴリズム"というこちらのqiitaの記事がよくまとまっている](https://qiita.com/nariaki3551/items/8694eee8793f88e89f41)

## ここから下は練習問題

In [20]:
#練習問題2-4
matrix = np.array([[1,2,3],[1,3,2],[3,1,2]])
print(matrix)
print("行列式 : ",linalg.det(matrix))

[[1 2 3]
 [1 3 2]
 [3 1 2]]
行列式 :  -12.000000000000002


In [21]:
#練習問題2-5
print('逆行列 : ', linalg.inv(matrix))
eigenvalues, eigenvectors = linalg.eig(matrix)
print('固有値 : ', eigenvalues)
print('固有ベクトル :')
print(eigenvectors)

逆行列 :  [[-0.333  0.083  0.417]
 [-0.333  0.583 -0.083]
 [ 0.667 -0.417 -0.083]]
固有値 :  [ 6.   +0.j -1.414+0.j  1.414+0.j]
固有ベクトル :
[[-0.577 -0.722  0.16 ]
 [-0.577 -0.143 -0.811]
 [-0.577  0.677  0.563]]


In [22]:
#練習問題2-6
def ft_2_6(x):
    return (x**3 + 2*x + 1)

print(newton(ft_2_6, 0))

-0.45339765151640365
