In [177]:
#この章で使用するライブラリ
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

In [178]:
# 可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

#小数点3位までの表示
%precision 3

'%.3f'

In [179]:
data = np.array([9,2,3,4,10,6,7,8,1,5])
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [180]:
data.dtype

dtype('int64')

In [181]:
print('次元数:', data.ndim)
print('要素数:', data.size)

次元数: 1
要素数: 10


In [182]:
data * 2

array([18,  4,  6,  8, 20, 12, 14, 16,  2, 10])

In [183]:
# .arrayはメソッド（関数）なので中括弧が必要
print('掛け算:',np.array([1,2,3,4,5,6,7,8,9,10]) * np.array([10,9,8,7,6,5,4,3,2,1]))

掛け算: [10 18 24 28 30 30 28 24 18 10]


In [184]:
print('累乗:',np.array([1,2,3,4,5,6,7,8,9,10]) ** 2)

累乗: [  1   4   9  16  25  36  49  64  81 100]


In [185]:
print('割り算:',np.array([1,2,3,4,5,6,7,8,9,10]) / np.array([10,9,8,7,6,5,4,3,2,1]))

割り算: [ 0.1    0.222  0.375  0.571  0.833  1.2    1.75   2.667  4.5   10.   ]


In [186]:
print(data)
data.sort()
data

[ 9  2  3  4 10  6  7  8  1  5]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [187]:
#逆順のソート
#[n,m,s] n番目からm-1番目をsずつ飛ばして取り出す。n,mを省略すると全ての意味になる
data[::-1].sort()
data

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [188]:
#最小値
print('min:', data.min())
#最大値
print('max:', data.max())
#合計
print('sum:', data.sum())
#積み上げ
print('cum:', data.cumsum())
#積み上げ割合
print('ratio:', data.cumsum()/ data.sum())

min: 1
max: 10
sum: 55
cum: [10 19 27 34 40 45 49 52 54 55]
ratio: [0.182 0.345 0.491 0.618 0.727 0.818 0.891 0.945 0.982 1.   ]


In [189]:
#乱数
random.seed(0)

#正規分布(平均0,分散1）の乱数を10個発生
rnd_data = random.randn(10)

print('乱数10個の配列:', rnd_data)

乱数10個の配列: [ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]


In [190]:
#データのランダム抽出
data = np.array([9,2,3,4,10,6,7,8,1,5])
print(random.choice(data, 10))
print(random.choice(data, 10, replace=False))

[ 7  8  8  1  2  6  5  1  5 10]
[10  2  7  8  3  1  6  5  9  4]


In [202]:
# #column
# #超高速なnumpy!!

# N = 10 ** 6
# #"_"と書くのはその後に変数を使用しないときの慣習
# normal_data = [random.random() for _ in range(N)]

# #numpy ver.
# nunpy_random_data = np.array(normal_data)

# #普通の処理
# %timeit sum(normal_data)

# #numpyの処理
# %timeit np.sum(nunpy_random_data)

In [203]:
#ここからは行列
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [204]:
array1 = np.arange(9).reshape(3,3)
print(array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [205]:
#1行目
array1[0,:]

array([0, 1, 2])

In [206]:
#1列目
array1[:,0]

array([0, 3, 6])

In [207]:
array2 = np.arange(9,18).reshape(3,3)
print(array2)

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [208]:
#行列の積（内積＝dot product）
np.dot(array1,array2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [209]:
#要素同士の積
array1 * array2

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [210]:
#要素が0や1の行列を作る
print(np.zeros((2,3), dtype = np.int64))
print(np.ones((2,3), dtype = np.float64))

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [214]:
#練習問題2-1
array21 = np.array([i for i in range(51)])
print(array03.sum())

1275


In [215]:
#練習問題2-2:正規分布に基づく乱数生成
array22 = random.randn(10)
print('最大値 : {0},最小値 : {1}, 合計 : {2}'.format(array22.max(), array22.min(), array22.sum()))
print(array22)

最大値 : 1.6811463415674608,最小値 : -2.0734877175678044, 合計 : -5.547306495698986
[-1.517 -0.623  0.21  -0.056  1.681 -1.075 -0.23  -2.073 -0.474 -1.392]


In [216]:
#練習問題2-3 : 行列を作成し、要素を2乗してみよう
array23 = np.array([3 for _ in range(9)]).reshape(3,3)
print(array23)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [217]:
array23 ** 2

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])